- name: Build ImmortalWrt-x86-64-ext4-efi
  run: |
    docker run --rm -i \
      --user root \
      -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
      -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
      -v "${{ github.workspace }}/x86-64/imm-ext4.config:/home/build/immortalwrt/.config" \
      -v "${{ github.workspace }}/x86-64/24.10/build.sh:/home/build/immortalwrt/build.sh" \
      -e PROFILE=${{ github.event.inputs.profile }} \
      -e INCLUDE_DOCKER=${{ github.event.inputs.include_docker }} \
      -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
      -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
      -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
      immortalwrt/imagebuilder:x86-64-openwrt-24.10.2 /bin/bash /home/build/immortalwrt/build.sh
